# Generated by Django 2.1.7 on 2022-01-24 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220124_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 24, 19, 58, 22, 20286)),
        ),
    ]
